# Generated by Django 3.2.3 on 2021-06-05 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
