# Generated by Django 3.2.3 on 2021-06-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("options", "0002_option_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="option",
            new_name="name",
        ),
    ]
