# Generated by Django 3.2.3 on 2021-06-07 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_menulinkperemployee"),
        ("employees", "0001_initial"),
        ("options", "0003_rename_option_option_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.employee",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="menus.menu"
                    ),
                ),
                (
                    "option_selected",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="options.option"
                    ),
                ),
            ],
        ),
    ]
