# Generated by Django 3.2.3 on 2021-06-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_employeeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeoption',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
