# Generated by Django 3.2.3 on 2021-06-07 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_employeeoption_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeoption',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
