# Generated by Django 3.2.3 on 2021-06-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
