# Generated by Django 3.2.3 on 2021-06-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menu_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
