# Generated by Django 3.2.3 on 2021-06-07 00:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("menus", "0003_delete_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuLinkperEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.employee",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="menus.menu"
                    ),
                ),
            ],
            options={
                "unique_together": {("menu", "employee")},
            },
        ),
    ]
