# Generated by Django 3.2.3 on 2021-06-07 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_menulinkperemployee"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="date_menu",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
